/********************************************************************************
** Form generated from reading UI file 'ScanMainGUI.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SCANMAINGUI_H
#define UI_SCANMAINGUI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ScanMainGUI
{
public:
    QGroupBox *ScanJawGroup;
    QLabel *ScanJawGroupTipImage;
    QPushButton *ScanJawScanBtn;
    QPushButton *ScanJawBackStepBtn;
    QLabel *ScanJawTips;
    QGroupBox *compensationScanPanel;
    QLabel *label_2;
    QPushButton *compensationScanPanelNextBtn;
    QPushButton *compensationScanPanelBackBtn;
    QLabel *compensationScanPanelTipLabel;
    QLabel *label_3;
    QLineEdit *rotationLineEdit;
    QLineEdit *waverLineEdit;
    QLabel *label_4;
    QPushButton *compensationBtn;
    QPushButton *discardBtn;
    QGroupBox *CutJawPanel;
    QLabel *label_5;
    QPushButton *cutPaneNextStepBtn;
    QPushButton *cutPanelBackBtn;
    QLabel *CutJawPanelTipsLabel;
    QLabel *label_6;
    QSlider *cutHeightSlider;
    QSpinBox *cutHeightSpinBox;
    QPushButton *cutModelBtn;
    QPushButton *unDoCutBtn;
    QPushButton *saveCutHeightCutBtn;
    QGroupBox *CutJawFinishPanel;
    QLabel *CutJawFinishPanelTips;
    QPushButton *CutJawFinishPanelNextStepBtn;
    QPushButton *CutJawFinishPanelBackBtn;
    QLabel *label_8;
    QLabel *CutJawFinishPanelTipImage;
    QGroupBox *StitchingPanel;
    QLabel *CutJawFinishPanelTips_3;
    QPushButton *stitchingPanelBtn;
    QPushButton *stitchingBackBtn;
    QLabel *StitchingPanelTips;
    QPushButton *manualStitchingBtn;
    QGroupBox *StitchingFinishPanel;
    QLabel *CutJawFinishPanelTips_5;
    QPushButton *stitchingFNextBtn;
    QPushButton *StitchingFinishPanelBackBtn;
    QLabel *StitchingPanelTips_3;
    QPushButton *stitchingUpperJawBtn;
    QPushButton *stitchingLowerJawBtn;
    QGroupBox *OralSubstitutePanel;
    QLabel *CutJawFinishPanelTips_4;
    QPushButton *OralSubstitutePanelNextBtn;
    QPushButton *oralSubstitutePanelBackBtn;
    QLabel *OralSubstitutePanel_2;
    QLabel *label;
    QLabel *teethNoLabel5;
    QLabel *teethNoLabel4;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *teethNoLabel3;
    QLabel *teethNoLabel2;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *teethNoLabel1;
    QLabel *teethNoLabel8;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *teethNoLabel6;
    QLabel *label_21;
    QLabel *teethNoLabel7;
    QGroupBox *TeethStitchingPanel;
    QLabel *CutJawFinishPanelTips_8;
    QPushButton *teethStitchingPanelNextBtn;
    QPushButton *teethStitchingPanelBackBtn;
    QLabel *StitchingPanelTips_4;

    void setupUi(QWidget *ScanMainGUI)
    {
        if (ScanMainGUI->objectName().isEmpty())
            ScanMainGUI->setObjectName(QStringLiteral("ScanMainGUI"));
        ScanMainGUI->resize(1844, 1080);
        ScanMainGUI->setMaximumSize(QSize(1920, 1080));
        ScanJawGroup = new QGroupBox(ScanMainGUI);
        ScanJawGroup->setObjectName(QStringLiteral("ScanJawGroup"));
        ScanJawGroup->setEnabled(true);
        ScanJawGroup->setGeometry(QRect(0, 0, 300, 700));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(245, 245, 245, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 0));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(247, 247, 247, 0));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(120, 120, 120, 0));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(160, 160, 160, 0));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(247, 247, 247, 127));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush9(QColor(240, 240, 240, 0));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        ScanJawGroup->setPalette(palette);
        ScanJawGroup->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(245,245,245);"));
        ScanJawGroupTipImage = new QLabel(ScanJawGroup);
        ScanJawGroupTipImage->setObjectName(QStringLiteral("ScanJawGroupTipImage"));
        ScanJawGroupTipImage->setGeometry(QRect(0, 180, 300, 102));
        ScanJawGroupTipImage->setPixmap(QPixmap(QString::fromUtf8("C:/Users/CAMNODE06/.designer/backup/Resources/images/lowerjaw_yes.png")));
        ScanJawGroupTipImage->setScaledContents(true);
        ScanJawScanBtn = new QPushButton(ScanJawGroup);
        ScanJawScanBtn->setObjectName(QStringLiteral("ScanJawScanBtn"));
        ScanJawScanBtn->setGeometry(QRect(40, 500, 221, 40));
        QPalette palette1;
        QBrush brush10(QColor(128, 128, 128, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush10);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        ScanJawScanBtn->setPalette(palette1);
        QFont font;
        font.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font.setPointSize(14);
        font.setBold(true);
        font.setWeight(75);
        ScanJawScanBtn->setFont(font);
        ScanJawScanBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        ScanJawBackStepBtn = new QPushButton(ScanJawGroup);
        ScanJawBackStepBtn->setObjectName(QStringLiteral("ScanJawBackStepBtn"));
        ScanJawBackStepBtn->setGeometry(QRect(40, 420, 221, 40));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush10);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        ScanJawBackStepBtn->setPalette(palette2);
        ScanJawBackStepBtn->setFont(font);
        ScanJawBackStepBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        ScanJawTips = new QLabel(ScanJawGroup);
        ScanJawTips->setObjectName(QStringLiteral("ScanJawTips"));
        ScanJawTips->setGeometry(QRect(10, 20, 271, 31));
        QPalette palette3;
        QBrush brush11(QColor(88, 88, 88, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        QBrush brush12(QColor(120, 120, 120, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        ScanJawTips->setPalette(palette3);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font1.setPointSize(14);
        ScanJawTips->setFont(font1);
        compensationScanPanel = new QGroupBox(ScanMainGUI);
        compensationScanPanel->setObjectName(QStringLiteral("compensationScanPanel"));
        compensationScanPanel->setEnabled(true);
        compensationScanPanel->setGeometry(QRect(1150, 360, 300, 700));
        compensationScanPanel->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(248,250,250);"));
        label_2 = new QLabel(compensationScanPanel);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 90, 281, 81));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        QBrush brush13(QColor(248, 250, 250, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        label_2->setPalette(palette4);
        QFont font2;
        font2.setFamily(QStringLiteral("Arial"));
        font2.setPointSize(14);
        label_2->setFont(font2);
        label_2->setWordWrap(true);
        compensationScanPanelNextBtn = new QPushButton(compensationScanPanel);
        compensationScanPanelNextBtn->setObjectName(QStringLiteral("compensationScanPanelNextBtn"));
        compensationScanPanelNextBtn->setGeometry(QRect(30, 620, 221, 40));
        compensationScanPanelNextBtn->setFont(font);
        compensationScanPanelNextBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        compensationScanPanelBackBtn = new QPushButton(compensationScanPanel);
        compensationScanPanelBackBtn->setObjectName(QStringLiteral("compensationScanPanelBackBtn"));
        compensationScanPanelBackBtn->setEnabled(true);
        compensationScanPanelBackBtn->setGeometry(QRect(30, 540, 221, 40));
        compensationScanPanelBackBtn->setFont(font);
        compensationScanPanelBackBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        compensationScanPanelTipLabel = new QLabel(compensationScanPanel);
        compensationScanPanelTipLabel->setObjectName(QStringLiteral("compensationScanPanelTipLabel"));
        compensationScanPanelTipLabel->setGeometry(QRect(0, 10, 271, 61));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        compensationScanPanelTipLabel->setPalette(palette5);
        QFont font3;
        font3.setFamily(QStringLiteral("Arial"));
        font3.setPointSize(18);
        compensationScanPanelTipLabel->setFont(font3);
        compensationScanPanelTipLabel->setScaledContents(false);
        compensationScanPanelTipLabel->setWordWrap(true);
        label_3 = new QLabel(compensationScanPanel);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 190, 61, 21));
        rotationLineEdit = new QLineEdit(compensationScanPanel);
        rotationLineEdit->setObjectName(QStringLiteral("rotationLineEdit"));
        rotationLineEdit->setGeometry(QRect(100, 190, 113, 20));
        waverLineEdit = new QLineEdit(compensationScanPanel);
        waverLineEdit->setObjectName(QStringLiteral("waverLineEdit"));
        waverLineEdit->setGeometry(QRect(100, 230, 113, 20));
        label_4 = new QLabel(compensationScanPanel);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 230, 61, 21));
        compensationBtn = new QPushButton(compensationScanPanel);
        compensationBtn->setObjectName(QStringLiteral("compensationBtn"));
        compensationBtn->setGeometry(QRect(30, 290, 221, 40));
        compensationBtn->setFont(font);
        compensationBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        discardBtn = new QPushButton(compensationScanPanel);
        discardBtn->setObjectName(QStringLiteral("discardBtn"));
        discardBtn->setGeometry(QRect(30, 360, 221, 40));
        discardBtn->setFont(font);
        discardBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        CutJawPanel = new QGroupBox(ScanMainGUI);
        CutJawPanel->setObjectName(QStringLiteral("CutJawPanel"));
        CutJawPanel->setEnabled(true);
        CutJawPanel->setGeometry(QRect(1150, 0, 300, 700));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush6);
        QBrush brush14(QColor(227, 235, 245, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        QBrush brush15(QColor(99, 107, 117, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush15);
        QBrush brush16(QColor(133, 143, 157, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush17(QColor(199, 215, 235, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        CutJawPanel->setPalette(palette6);
        CutJawPanel->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(248,250,250);"));
        label_5 = new QLabel(CutJawPanel);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 90, 281, 51));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        label_5->setPalette(palette7);
        label_5->setFont(font2);
        label_5->setWordWrap(true);
        cutPaneNextStepBtn = new QPushButton(CutJawPanel);
        cutPaneNextStepBtn->setObjectName(QStringLiteral("cutPaneNextStepBtn"));
        cutPaneNextStepBtn->setGeometry(QRect(30, 610, 221, 40));
        cutPaneNextStepBtn->setFont(font);
        cutPaneNextStepBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        cutPanelBackBtn = new QPushButton(CutJawPanel);
        cutPanelBackBtn->setObjectName(QStringLiteral("cutPanelBackBtn"));
        cutPanelBackBtn->setGeometry(QRect(30, 530, 221, 40));
        cutPanelBackBtn->setFont(font);
        cutPanelBackBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        CutJawPanelTipsLabel = new QLabel(CutJawPanel);
        CutJawPanelTipsLabel->setObjectName(QStringLiteral("CutJawPanelTipsLabel"));
        CutJawPanelTipsLabel->setGeometry(QRect(10, 10, 281, 61));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        CutJawPanelTipsLabel->setPalette(palette8);
        CutJawPanelTipsLabel->setFont(font2);
        CutJawPanelTipsLabel->setWordWrap(true);
        label_6 = new QLabel(CutJawPanel);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 230, 61, 21));
        cutHeightSlider = new QSlider(CutJawPanel);
        cutHeightSlider->setObjectName(QStringLiteral("cutHeightSlider"));
        cutHeightSlider->setGeometry(QRect(140, 230, 151, 22));
        cutHeightSlider->setMinimum(-50);
        cutHeightSlider->setMaximum(50);
        cutHeightSlider->setOrientation(Qt::Horizontal);
        cutHeightSpinBox = new QSpinBox(CutJawPanel);
        cutHeightSpinBox->setObjectName(QStringLiteral("cutHeightSpinBox"));
        cutHeightSpinBox->setGeometry(QRect(70, 230, 51, 22));
        cutHeightSpinBox->setMinimum(-50);
        cutHeightSpinBox->setMaximum(50);
        cutModelBtn = new QPushButton(CutJawPanel);
        cutModelBtn->setObjectName(QStringLiteral("cutModelBtn"));
        cutModelBtn->setGeometry(QRect(30, 290, 221, 40));
        cutModelBtn->setFont(font);
        cutModelBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        unDoCutBtn = new QPushButton(CutJawPanel);
        unDoCutBtn->setObjectName(QStringLiteral("unDoCutBtn"));
        unDoCutBtn->setGeometry(QRect(30, 370, 221, 40));
        unDoCutBtn->setFont(font);
        unDoCutBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        saveCutHeightCutBtn = new QPushButton(CutJawPanel);
        saveCutHeightCutBtn->setObjectName(QStringLiteral("saveCutHeightCutBtn"));
        saveCutHeightCutBtn->setGeometry(QRect(30, 450, 221, 40));
        saveCutHeightCutBtn->setFont(font);
        saveCutHeightCutBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        CutJawFinishPanel = new QGroupBox(ScanMainGUI);
        CutJawFinishPanel->setObjectName(QStringLiteral("CutJawFinishPanel"));
        CutJawFinishPanel->setEnabled(true);
        CutJawFinishPanel->setGeometry(QRect(870, 220, 300, 700));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush15);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        CutJawFinishPanel->setPalette(palette9);
        CutJawFinishPanel->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(248,250,250);"));
        CutJawFinishPanelTips = new QLabel(CutJawFinishPanel);
        CutJawFinishPanelTips->setObjectName(QStringLiteral("CutJawFinishPanelTips"));
        CutJawFinishPanelTips->setGeometry(QRect(10, 90, 281, 51));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        CutJawFinishPanelTips->setPalette(palette10);
        CutJawFinishPanelTips->setFont(font2);
        CutJawFinishPanelTips->setWordWrap(true);
        CutJawFinishPanelNextStepBtn = new QPushButton(CutJawFinishPanel);
        CutJawFinishPanelNextStepBtn->setObjectName(QStringLiteral("CutJawFinishPanelNextStepBtn"));
        CutJawFinishPanelNextStepBtn->setGeometry(QRect(40, 580, 221, 40));
        CutJawFinishPanelNextStepBtn->setFont(font);
        CutJawFinishPanelNextStepBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        CutJawFinishPanelBackBtn = new QPushButton(CutJawFinishPanel);
        CutJawFinishPanelBackBtn->setObjectName(QStringLiteral("CutJawFinishPanelBackBtn"));
        CutJawFinishPanelBackBtn->setGeometry(QRect(40, 470, 221, 40));
        CutJawFinishPanelBackBtn->setFont(font);
        CutJawFinishPanelBackBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        label_8 = new QLabel(CutJawFinishPanel);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 10, 281, 61));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        label_8->setPalette(palette11);
        label_8->setFont(font2);
        label_8->setWordWrap(true);
        CutJawFinishPanelTipImage = new QLabel(CutJawFinishPanel);
        CutJawFinishPanelTipImage->setObjectName(QStringLiteral("CutJawFinishPanelTipImage"));
        CutJawFinishPanelTipImage->setGeometry(QRect(10, 150, 271, 291));
        CutJawFinishPanelTipImage->setPixmap(QPixmap(QString::fromUtf8("C:/Users/CAMNODE06/.designer/backup/Resources/images/alljaw.png")));
        CutJawFinishPanelTipImage->setScaledContents(true);
        StitchingPanel = new QGroupBox(ScanMainGUI);
        StitchingPanel->setObjectName(QStringLiteral("StitchingPanel"));
        StitchingPanel->setEnabled(true);
        StitchingPanel->setGeometry(QRect(590, 300, 300, 700));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush15);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        StitchingPanel->setPalette(palette12);
        StitchingPanel->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(248,250,250);"));
        CutJawFinishPanelTips_3 = new QLabel(StitchingPanel);
        CutJawFinishPanelTips_3->setObjectName(QStringLiteral("CutJawFinishPanelTips_3"));
        CutJawFinishPanelTips_3->setGeometry(QRect(10, 90, 281, 51));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        CutJawFinishPanelTips_3->setPalette(palette13);
        CutJawFinishPanelTips_3->setFont(font2);
        CutJawFinishPanelTips_3->setToolTipDuration(-3);
        CutJawFinishPanelTips_3->setWordWrap(true);
        stitchingPanelBtn = new QPushButton(StitchingPanel);
        stitchingPanelBtn->setObjectName(QStringLiteral("stitchingPanelBtn"));
        stitchingPanelBtn->setGeometry(QRect(40, 540, 221, 40));
        stitchingPanelBtn->setFont(font);
        stitchingPanelBtn->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);\n"
""));
        stitchingBackBtn = new QPushButton(StitchingPanel);
        stitchingBackBtn->setObjectName(QStringLiteral("stitchingBackBtn"));
        stitchingBackBtn->setGeometry(QRect(40, 400, 221, 40));
        stitchingBackBtn->setFont(font);
        stitchingBackBtn->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);\n"
""));
        StitchingPanelTips = new QLabel(StitchingPanel);
        StitchingPanelTips->setObjectName(QStringLiteral("StitchingPanelTips"));
        StitchingPanelTips->setGeometry(QRect(10, 10, 281, 61));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        StitchingPanelTips->setPalette(palette14);
        StitchingPanelTips->setFont(font2);
        StitchingPanelTips->setWordWrap(true);
        manualStitchingBtn = new QPushButton(StitchingPanel);
        manualStitchingBtn->setObjectName(QStringLiteral("manualStitchingBtn"));
        manualStitchingBtn->setGeometry(QRect(40, 270, 221, 40));
        manualStitchingBtn->setFont(font);
        manualStitchingBtn->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);\n"
""));
        StitchingFinishPanel = new QGroupBox(ScanMainGUI);
        StitchingFinishPanel->setObjectName(QStringLiteral("StitchingFinishPanel"));
        StitchingFinishPanel->setEnabled(true);
        StitchingFinishPanel->setGeometry(QRect(1460, 0, 300, 700));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush15);
        palette15.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush);
        palette15.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette15.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette15.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette15.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette15.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette15.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        StitchingFinishPanel->setPalette(palette15);
        StitchingFinishPanel->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(248,250,250);"));
        CutJawFinishPanelTips_5 = new QLabel(StitchingFinishPanel);
        CutJawFinishPanelTips_5->setObjectName(QStringLiteral("CutJawFinishPanelTips_5"));
        CutJawFinishPanelTips_5->setGeometry(QRect(10, 90, 281, 51));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        CutJawFinishPanelTips_5->setPalette(palette16);
        CutJawFinishPanelTips_5->setFont(font2);
        CutJawFinishPanelTips_5->setToolTipDuration(-3);
        CutJawFinishPanelTips_5->setWordWrap(true);
        stitchingFNextBtn = new QPushButton(StitchingFinishPanel);
        stitchingFNextBtn->setObjectName(QStringLiteral("stitchingFNextBtn"));
        stitchingFNextBtn->setGeometry(QRect(50, 620, 221, 40));
        stitchingFNextBtn->setFont(font);
        stitchingFNextBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        StitchingFinishPanelBackBtn = new QPushButton(StitchingFinishPanel);
        StitchingFinishPanelBackBtn->setObjectName(QStringLiteral("StitchingFinishPanelBackBtn"));
        StitchingFinishPanelBackBtn->setGeometry(QRect(50, 530, 221, 40));
        StitchingFinishPanelBackBtn->setFont(font);
        StitchingFinishPanelBackBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        StitchingPanelTips_3 = new QLabel(StitchingFinishPanel);
        StitchingPanelTips_3->setObjectName(QStringLiteral("StitchingPanelTips_3"));
        StitchingPanelTips_3->setGeometry(QRect(10, 10, 281, 61));
        QPalette palette17;
        QBrush brush18(QColor(85, 88, 88, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush18);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush18);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        StitchingPanelTips_3->setPalette(palette17);
        StitchingPanelTips_3->setFont(font2);
        StitchingPanelTips_3->setWordWrap(true);
        stitchingUpperJawBtn = new QPushButton(StitchingFinishPanel);
        stitchingUpperJawBtn->setObjectName(QStringLiteral("stitchingUpperJawBtn"));
        stitchingUpperJawBtn->setGeometry(QRect(40, 160, 221, 40));
        stitchingUpperJawBtn->setFont(font);
        stitchingUpperJawBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        stitchingUpperJawBtn->setCheckable(true);
        stitchingLowerJawBtn = new QPushButton(StitchingFinishPanel);
        stitchingLowerJawBtn->setObjectName(QStringLiteral("stitchingLowerJawBtn"));
        stitchingLowerJawBtn->setGeometry(QRect(40, 240, 221, 40));
        stitchingLowerJawBtn->setFont(font);
        stitchingLowerJawBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        stitchingLowerJawBtn->setCheckable(true);
        OralSubstitutePanel = new QGroupBox(ScanMainGUI);
        OralSubstitutePanel->setObjectName(QStringLiteral("OralSubstitutePanel"));
        OralSubstitutePanel->setEnabled(true);
        OralSubstitutePanel->setGeometry(QRect(300, -20, 300, 700));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette18.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        palette18.setBrush(QPalette::Active, QPalette::Dark, brush15);
        palette18.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush);
        palette18.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette18.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette18.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette18.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette18.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette18.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette18.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette18.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette18.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette18.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        OralSubstitutePanel->setPalette(palette18);
        OralSubstitutePanel->setAutoFillBackground(false);
        OralSubstitutePanel->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(248,250,250);"));
        CutJawFinishPanelTips_4 = new QLabel(OralSubstitutePanel);
        CutJawFinishPanelTips_4->setObjectName(QStringLiteral("CutJawFinishPanelTips_4"));
        CutJawFinishPanelTips_4->setGeometry(QRect(10, 70, 281, 51));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette19.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        CutJawFinishPanelTips_4->setPalette(palette19);
        CutJawFinishPanelTips_4->setFont(font1);
        CutJawFinishPanelTips_4->setToolTipDuration(-3);
        CutJawFinishPanelTips_4->setWordWrap(true);
        OralSubstitutePanelNextBtn = new QPushButton(OralSubstitutePanel);
        OralSubstitutePanelNextBtn->setObjectName(QStringLiteral("OralSubstitutePanelNextBtn"));
        OralSubstitutePanelNextBtn->setGeometry(QRect(30, 590, 221, 40));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette20.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush10);
        palette20.setBrush(QPalette::Active, QPalette::ButtonText, brush10);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush10);
        palette20.setBrush(QPalette::Inactive, QPalette::ButtonText, brush10);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush10);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette20.setBrush(QPalette::Disabled, QPalette::ButtonText, brush10);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        OralSubstitutePanelNextBtn->setPalette(palette20);
        OralSubstitutePanelNextBtn->setFont(font);
        OralSubstitutePanelNextBtn->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);\n"
""));
        oralSubstitutePanelBackBtn = new QPushButton(OralSubstitutePanel);
        oralSubstitutePanelBackBtn->setObjectName(QStringLiteral("oralSubstitutePanelBackBtn"));
        oralSubstitutePanelBackBtn->setGeometry(QRect(30, 470, 221, 40));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette21.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush10);
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush10);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush10);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush10);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush10);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush10);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        oralSubstitutePanelBackBtn->setPalette(palette21);
        oralSubstitutePanelBackBtn->setFont(font);
        oralSubstitutePanelBackBtn->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);\n"
""));
        OralSubstitutePanel_2 = new QLabel(OralSubstitutePanel);
        OralSubstitutePanel_2->setObjectName(QStringLiteral("OralSubstitutePanel_2"));
        OralSubstitutePanel_2->setGeometry(QRect(10, 10, 281, 61));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette22.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        OralSubstitutePanel_2->setPalette(palette22);
        OralSubstitutePanel_2->setFont(font1);
        OralSubstitutePanel_2->setWordWrap(true);
        label = new QLabel(OralSubstitutePanel);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(150, 120, 30, 20));
        teethNoLabel5 = new QLabel(OralSubstitutePanel);
        teethNoLabel5->setObjectName(QStringLiteral("teethNoLabel5"));
        teethNoLabel5->setGeometry(QRect(110, 140, 30, 20));
        teethNoLabel4 = new QLabel(OralSubstitutePanel);
        teethNoLabel4->setObjectName(QStringLiteral("teethNoLabel4"));
        teethNoLabel4->setGeometry(QRect(210, 190, 30, 20));
        label_10 = new QLabel(OralSubstitutePanel);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(250, 170, 30, 20));
        label_11 = new QLabel(OralSubstitutePanel);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(250, 260, 30, 20));
        teethNoLabel3 = new QLabel(OralSubstitutePanel);
        teethNoLabel3->setObjectName(QStringLiteral("teethNoLabel3"));
        teethNoLabel3->setGeometry(QRect(210, 280, 30, 20));
        teethNoLabel2 = new QLabel(OralSubstitutePanel);
        teethNoLabel2->setObjectName(QStringLiteral("teethNoLabel2"));
        teethNoLabel2->setGeometry(QRect(120, 350, 30, 20));
        label_14 = new QLabel(OralSubstitutePanel);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(160, 320, 30, 20));
        label_15 = new QLabel(OralSubstitutePanel);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(90, 320, 30, 20));
        teethNoLabel1 = new QLabel(OralSubstitutePanel);
        teethNoLabel1->setObjectName(QStringLiteral("teethNoLabel1"));
        teethNoLabel1->setGeometry(QRect(120, 240, 30, 20));
        teethNoLabel8 = new QLabel(OralSubstitutePanel);
        teethNoLabel8->setObjectName(QStringLiteral("teethNoLabel8"));
        teethNoLabel8->setGeometry(QRect(50, 340, 30, 20));
        label_18 = new QLabel(OralSubstitutePanel);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(150, 220, 30, 20));
        label_19 = new QLabel(OralSubstitutePanel);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(50, 161, 30, 20));
        teethNoLabel6 = new QLabel(OralSubstitutePanel);
        teethNoLabel6->setObjectName(QStringLiteral("teethNoLabel6"));
        teethNoLabel6->setGeometry(QRect(10, 190, 30, 20));
        label_21 = new QLabel(OralSubstitutePanel);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(50, 251, 30, 20));
        teethNoLabel7 = new QLabel(OralSubstitutePanel);
        teethNoLabel7->setObjectName(QStringLiteral("teethNoLabel7"));
        teethNoLabel7->setGeometry(QRect(10, 280, 30, 20));
        TeethStitchingPanel = new QGroupBox(ScanMainGUI);
        TeethStitchingPanel->setObjectName(QStringLiteral("TeethStitchingPanel"));
        TeethStitchingPanel->setEnabled(true);
        TeethStitchingPanel->setGeometry(QRect(20, 530, 300, 700));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette23.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette23.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        palette23.setBrush(QPalette::Active, QPalette::Dark, brush15);
        palette23.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette23.setBrush(QPalette::Active, QPalette::Text, brush);
        palette23.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette23.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette23.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette23.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette23.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette23.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette23.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette23.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette23.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette23.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette23.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette23.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette23.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette23.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette23.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette23.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette23.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette23.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette23.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette23.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette23.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette23.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette23.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette23.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette23.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        palette23.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette23.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette23.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        TeethStitchingPanel->setPalette(palette23);
        TeethStitchingPanel->setStyleSheet(QLatin1String("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);\n"
"background-color:rgb(248,250,250);"));
        CutJawFinishPanelTips_8 = new QLabel(TeethStitchingPanel);
        CutJawFinishPanelTips_8->setObjectName(QStringLiteral("CutJawFinishPanelTips_8"));
        CutJawFinishPanelTips_8->setGeometry(QRect(10, 90, 281, 51));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette24.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette24.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette24.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette24.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette24.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        CutJawFinishPanelTips_8->setPalette(palette24);
        CutJawFinishPanelTips_8->setFont(font1);
        CutJawFinishPanelTips_8->setToolTipDuration(-3);
        CutJawFinishPanelTips_8->setWordWrap(true);
        teethStitchingPanelNextBtn = new QPushButton(TeethStitchingPanel);
        teethStitchingPanelNextBtn->setObjectName(QStringLiteral("teethStitchingPanelNextBtn"));
        teethStitchingPanelNextBtn->setGeometry(QRect(30, 450, 221, 40));
        teethStitchingPanelNextBtn->setFont(font);
        teethStitchingPanelNextBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        teethStitchingPanelBackBtn = new QPushButton(TeethStitchingPanel);
        teethStitchingPanelBackBtn->setObjectName(QStringLiteral("teethStitchingPanelBackBtn"));
        teethStitchingPanelBackBtn->setGeometry(QRect(30, 320, 221, 40));
        teethStitchingPanelBackBtn->setFont(font);
        teethStitchingPanelBackBtn->setStyleSheet(QStringLiteral("border:0px groove gray;border-radius:5px;padding:2px 4px;border-color: rgb(128, 128, 128);background: rgb(255, 255, 255);color:rgb(128,128,128);"));
        StitchingPanelTips_4 = new QLabel(TeethStitchingPanel);
        StitchingPanelTips_4->setObjectName(QStringLiteral("StitchingPanelTips_4"));
        StitchingPanelTips_4->setGeometry(QRect(10, 10, 251, 61));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette25.setBrush(QPalette::Active, QPalette::Button, brush13);
        palette25.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette25.setBrush(QPalette::Active, QPalette::Window, brush13);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush13);
        palette25.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette25.setBrush(QPalette::Inactive, QPalette::Window, brush13);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush13);
        palette25.setBrush(QPalette::Disabled, QPalette::Base, brush13);
        palette25.setBrush(QPalette::Disabled, QPalette::Window, brush13);
        StitchingPanelTips_4->setPalette(palette25);
        StitchingPanelTips_4->setFont(font1);
        StitchingPanelTips_4->setWordWrap(true);
        compensationScanPanel->raise();
        ScanJawGroup->raise();
        CutJawFinishPanel->raise();
        StitchingPanel->raise();
        StitchingFinishPanel->raise();
        OralSubstitutePanel->raise();
        TeethStitchingPanel->raise();
        CutJawPanel->raise();

        retranslateUi(ScanMainGUI);

        QMetaObject::connectSlotsByName(ScanMainGUI);
    } // setupUi

    void retranslateUi(QWidget *ScanMainGUI)
    {
        ScanMainGUI->setWindowTitle(QApplication::translate("ScanMainGUI", "ScanMainGUI", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        ScanMainGUI->setToolTip(QApplication::translate("ScanMainGUI", "\347\241\256\350\256\244\351\200\211\346\213\251", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        ScanJawGroup->setTitle(QString());
        ScanJawGroupTipImage->setText(QString());
#ifndef QT_NO_TOOLTIP
        ScanJawScanBtn->setToolTip(QApplication::translate("ScanMainGUI", "\346\211\253\346\217\217", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        ScanJawScanBtn->setText(QApplication::translate("ScanMainGUI", "\346\211\253     \346\217\217", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        ScanJawBackStepBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\212\344\270\200\346\255\245", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        ScanJawBackStepBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\212\344\270\200\346\255\245", Q_NULLPTR));
        ScanJawTips->setText(QApplication::translate("ScanMainGUI", "\344\270\212\351\242\214\346\250\241\345\236\213", Q_NULLPTR));
        compensationScanPanel->setTitle(QString());
        label_2->setText(QApplication::translate("ScanMainGUI", "\346\227\213\350\275\254\346\250\241\345\236\213\345\210\260\344\275\240\346\203\263\350\246\201\345\242\236\345\212\240\346\211\253\346\217\217\347\232\204\344\275\215\347\275\256\357\274\214\351\200\232\350\277\207\342\200\234\345\242\236\345\212\240\350\241\245\346\211\253\342\200\235\345\217\257\346\267\273\345\212\240\346\226\260\346\211\253\346\217\217\346\225\260\346\215\256", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        compensationScanPanelNextBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        compensationScanPanelNextBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        compensationScanPanelBackBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\220\216\351\200\200", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        compensationScanPanelBackBtn->setText(QApplication::translate("ScanMainGUI", "\345\220\216     \351\200\200", Q_NULLPTR));
        compensationScanPanelTipLabel->setText(QApplication::translate("ScanMainGUI", "\344\270\212\351\242\214\346\250\241\345\236\213\346\211\253\346\217\217\345\256\214\346\210\220\357\274\214\345\217\257\344\273\245\345\242\236\345\212\240\346\250\241\345\236\213\346\225\260\346\215\256", Q_NULLPTR));
        label_3->setText(QApplication::translate("ScanMainGUI", "\346\227\213\350\275\254\350\247\222\345\272\246", Q_NULLPTR));
        label_4->setText(QApplication::translate("ScanMainGUI", "\346\221\206\345\212\250\350\247\222\345\272\246", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        compensationBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\242\236\345\212\240\346\211\253\346\217\217", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        compensationBtn->setText(QApplication::translate("ScanMainGUI", "\345\242\236\345\212\240\346\211\253\346\217\217", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        discardBtn->setToolTip(QApplication::translate("ScanMainGUI", "\346\222\244\351\224\200\350\241\245\346\211\253", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        discardBtn->setText(QApplication::translate("ScanMainGUI", "\346\222\244\351\224\200\350\241\245\346\211\253", Q_NULLPTR));
        CutJawPanel->setTitle(QString());
        label_5->setText(QApplication::translate("ScanMainGUI", "\350\260\203\346\225\264\346\260\264\345\271\263\345\210\207\345\211\262\345\271\263\351\235\242\347\232\204\344\275\215\347\275\256\357\274\214\351\200\232\350\277\207\342\200\234\345\210\207\345\211\262\346\250\241\345\236\213\342\200\235\345\217\257\344\277\256\345\211\252\346\250\241\345\236\213\346\225\260\346\215\256", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        cutPaneNextStepBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        cutPaneNextStepBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        cutPanelBackBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\220\216\351\200\200", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        cutPanelBackBtn->setText(QApplication::translate("ScanMainGUI", "\345\220\216     \351\200\200", Q_NULLPTR));
        CutJawPanelTipsLabel->setText(QApplication::translate("ScanMainGUI", "\344\270\212\345\222\214\346\250\241\345\236\213\345\242\236\345\212\240\346\211\253\346\217\217\345\256\214\346\210\220\357\274\214\345\217\257\344\273\245\346\260\264\345\271\263\345\210\207\345\211\262\346\250\241\345\236\213\346\225\260\346\215\256", Q_NULLPTR));
        label_6->setText(QApplication::translate("ScanMainGUI", "\345\210\207\345\211\262\351\253\230\345\272\246", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        cutModelBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\210\207\345\211\262\346\250\241\345\236\213", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        cutModelBtn->setText(QApplication::translate("ScanMainGUI", "\345\210\207\345\211\262\346\250\241\345\236\213", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        unDoCutBtn->setToolTip(QApplication::translate("ScanMainGUI", "\346\222\244\351\224\200\345\210\207\345\211\262", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        unDoCutBtn->setText(QApplication::translate("ScanMainGUI", "\346\222\244\351\224\200\345\210\207\345\211\262", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        saveCutHeightCutBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\277\235\345\255\230\351\273\230\350\256\244\345\210\207\345\211\262\351\253\230\345\272\246", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        saveCutHeightCutBtn->setText(QApplication::translate("ScanMainGUI", "\344\277\235\345\255\230\344\270\272\351\273\230\350\256\244\345\210\207\345\211\262\351\253\230\345\272\246", Q_NULLPTR));
        CutJawFinishPanel->setTitle(QString());
        CutJawFinishPanelTips->setText(QApplication::translate("ScanMainGUI", "\345\217\257\344\273\245\351\200\232\350\277\207\345\267\245\345\205\267\346\240\217\344\277\256\345\211\252\344\270\212\351\242\214\346\250\241\345\236\213\346\225\260\346\215\256", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        CutJawFinishPanelNextStepBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\256\214\346\210\220", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        CutJawFinishPanelNextStepBtn->setText(QApplication::translate("ScanMainGUI", "\345\256\214     \346\210\220", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        CutJawFinishPanelBackBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\220\216\351\200\200", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        CutJawFinishPanelBackBtn->setText(QApplication::translate("ScanMainGUI", "\345\220\216     \351\200\200", Q_NULLPTR));
        label_8->setText(QApplication::translate("ScanMainGUI", "\346\213\274\346\216\245\345\256\214\346\210\220", Q_NULLPTR));
        CutJawFinishPanelTipImage->setText(QString());
        StitchingPanel->setTitle(QString());
        CutJawFinishPanelTips_3->setText(QApplication::translate("ScanMainGUI", "\345\217\214\345\207\273\350\216\267\345\217\2263\347\273\204\345\257\271\345\272\224\347\202\271", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        stitchingPanelBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        stitchingPanelBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        stitchingBackBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\220\216\351\200\200", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        stitchingBackBtn->setText(QApplication::translate("ScanMainGUI", "\345\220\216     \351\200\200", Q_NULLPTR));
        StitchingPanelTips->setText(QApplication::translate("ScanMainGUI", "\346\213\274\346\216\245\344\270\212\351\242\214\346\250\241\345\236\213", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        manualStitchingBtn->setToolTip(QApplication::translate("ScanMainGUI", "\346\211\213\345\212\250\346\213\274\346\216\245", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        manualStitchingBtn->setText(QApplication::translate("ScanMainGUI", "\346\211\213\345\212\250\346\213\274\346\216\245", Q_NULLPTR));
        StitchingFinishPanel->setTitle(QString());
        CutJawFinishPanelTips_5->setText(QApplication::translate("ScanMainGUI", "\345\217\257\344\273\245\344\277\256\345\211\252\346\250\241\345\236\213\346\225\260\346\215\256", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        stitchingFNextBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\256\214\346\210\220", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        stitchingFNextBtn->setText(QApplication::translate("ScanMainGUI", "\345\256\214     \346\210\220", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        StitchingFinishPanelBackBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\220\216\351\200\200", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        StitchingFinishPanelBackBtn->setText(QApplication::translate("ScanMainGUI", "\345\220\216     \351\200\200", Q_NULLPTR));
        StitchingPanelTips_3->setText(QApplication::translate("ScanMainGUI", "\345\256\214\346\210\220", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        stitchingUpperJawBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\212\351\242\214", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        stitchingUpperJawBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\212     \351\242\214", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        stitchingLowerJawBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\213\351\242\214", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        stitchingLowerJawBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\213     \351\242\214", Q_NULLPTR));
        OralSubstitutePanel->setTitle(QString());
        CutJawFinishPanelTips_4->setText(QApplication::translate("ScanMainGUI", "\345\215\225\345\207\273\345\255\224\344\275\215,\345\234\250\346\250\241\345\236\213\344\270\212\346\240\207\350\256\260\347\211\231\351\275\277", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        OralSubstitutePanelNextBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        OralSubstitutePanelNextBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        oralSubstitutePanelBackBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\220\216\351\200\200", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        oralSubstitutePanelBackBtn->setText(QApplication::translate("ScanMainGUI", "\345\220\216     \351\200\200", Q_NULLPTR));
        OralSubstitutePanel_2->setText(QApplication::translate("ScanMainGUI", "\350\257\267\346\217\222\345\205\245\344\273\243\345\236\213\347\233\230", Q_NULLPTR));
        label->setText(QApplication::translate("ScanMainGUI", "5", Q_NULLPTR));
        teethNoLabel5->setText(QApplication::translate("ScanMainGUI", "17", Q_NULLPTR));
        teethNoLabel4->setText(QApplication::translate("ScanMainGUI", "16", Q_NULLPTR));
        label_10->setText(QApplication::translate("ScanMainGUI", "4", Q_NULLPTR));
        label_11->setText(QApplication::translate("ScanMainGUI", "3", Q_NULLPTR));
        teethNoLabel3->setText(QApplication::translate("ScanMainGUI", "15", Q_NULLPTR));
        teethNoLabel2->setText(QApplication::translate("ScanMainGUI", "14", Q_NULLPTR));
        label_14->setText(QApplication::translate("ScanMainGUI", "2", Q_NULLPTR));
        label_15->setText(QApplication::translate("ScanMainGUI", "1", Q_NULLPTR));
        teethNoLabel1->setText(QApplication::translate("ScanMainGUI", "13", Q_NULLPTR));
        teethNoLabel8->setText(QApplication::translate("ScanMainGUI", "20", Q_NULLPTR));
        label_18->setText(QApplication::translate("ScanMainGUI", "8", Q_NULLPTR));
        label_19->setText(QApplication::translate("ScanMainGUI", "6", Q_NULLPTR));
        teethNoLabel6->setText(QApplication::translate("ScanMainGUI", "18", Q_NULLPTR));
        label_21->setText(QApplication::translate("ScanMainGUI", "7", Q_NULLPTR));
        teethNoLabel7->setText(QApplication::translate("ScanMainGUI", "19", Q_NULLPTR));
        TeethStitchingPanel->setTitle(QString());
        CutJawFinishPanelTips_8->setText(QApplication::translate("ScanMainGUI", "\345\217\214\345\207\273\350\216\267\345\217\2263\347\273\204\345\257\271\345\272\224\347\202\271", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        teethStitchingPanelNextBtn->setToolTip(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        teethStitchingPanelNextBtn->setText(QApplication::translate("ScanMainGUI", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        teethStitchingPanelBackBtn->setToolTip(QApplication::translate("ScanMainGUI", "\345\220\216\351\200\200", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        teethStitchingPanelBackBtn->setText(QApplication::translate("ScanMainGUI", "\345\220\216     \351\200\200", Q_NULLPTR));
        StitchingPanelTips_4->setText(QApplication::translate("ScanMainGUI", "\346\211\213\345\212\250\346\213\274\346\216\245", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ScanMainGUI: public Ui_ScanMainGUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SCANMAINGUI_H
